<a href="https://colab.research.google.com/github/spr-att/spra-tt.github.io/blob/main/AMLProject4_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import re
import nltk
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score as AC, confusion_matrix as CM
from tqdm import tqdm

In [ ]:
def modelvalidation(model,x,y,nfolds=5,rs=123):
  skf = StratifiedKFold(n_splits=nfolds,shuffle=True,random_state=rs)
  accuracies = []
  confusions = []

  for idxtrain, idxtest in tqdm(skf.split(x,y)):
    xtrain = x[idxtrain]
    ytrain = y[idxtrain]
    xtest = x[idxtest]
    ytest = y[idxtest]
    model.fit(xtrain,ytrain)
    accuracies.append(AC(ytest,model.predict(xtest)))
    print(accuracies)
    confusions.append(CM(ytest,model.predict(xtest)))
  return accuracies, confusions

The goal is to create a model that can predict the ClassificationLabel with great accuracy given the information in the rest of the columns.

For the project you will have to make your own research approach to pre-processing of the data, the design, and testing different good models (Logistic Regression, Random forest, SVM, KNN) for classification. The results need to be validated and professionally presented, including confusion matrices and accuracies. 

Hint: A good model will yield an overall cross-validated accuracy of at least 96%. A model that might perform well: KNN(5 neighbors, weights = distance).

In [ ]:
data = data = pd.read_csv('/content/drive/MyDrive/AML/Project4_Data.csv')

In [ ]:
data

Col1      Col2       Col3  \
0                      Word1 Word2 Word3 Word4 Word5  44912133   3,575.00   
1                                        Word6 Word7     10719   1,092.50   
2                    Word8 Word9 Word10 Word11 Word5  4.80Z+11         75   
3                                Word12 Word13 Word7     10731  30,980.00   
4                    Word8 Word9 Word10 Word11 Word5  4.80F+11   3,766.80   
...                                              ...       ...        ...   
5894                   Word177 Word178 Word147 Word7    180LSY  16,880.00   
5895                      Word16 Word17 Word18 Word7     BL398   4,200.00   
5896  Word212 Word213 Word214 Word125 Word119 Word39     74211        170   
5897                            Word148 Word75 Word5     11695  14,376.00   
5898                       Word40 Word41 Word4 Word5      1868   1,820.00   

                                       Col4        Col5  \
0                           Word771 Word772   8/31/2018   
1                   Word711 Word773 Word774   8/31/2018   
2                           Word775 Word776  10/31/2018   
3     Word777 Word45 Word160 Word45 Word778    1/1/2018   
4                   Word779 Word258 Word780    1/1/2018   
...                                     ...         ...   
5894               Word2127 Word705 Word825    3/1/2018   
5895          Word785 Word330 Word99 Word26   6/30/2018   
5896              Word1018 Word190 Word1403    1/1/2018   
5897                        Word846 Word991    4/1/2018   
5898       Word802 Word278 Word1242 Word803   7/31/2018   

                                         Col6   Col7 ClassificationLabel  
0             Word560 Word561 Word366 Word562   Doc1          Category_1  
1                     Word563 Word366 Word562  NoDoc          Category_2  
2                Word563 Word564 Word9 Word26  NoDoc          Category_1  
3                             Word565 Word566  NoDoc          Category_1  
4             Word567 Word568 Word569 Word570   Doc1          Category_1  
...                                       ...    ...                 ...  
5894                  Word576 Word366 Word562   Doc3          Category_1  
5895             Word563 Word564 Word9 Word26  NoDoc          Category_1  
5896                  Word563 Word608 Word609  NoDoc          Category_2  
5897          Word560 Word561 Word315 Word638   Doc1          Category_1  
5898  Word567 Word582 Word580 Word202 Word545   Doc1          Category_1  

[5899 rows x 8 columns]

In [ ]:
data['ClassificationLabel'] = data['ClassificationLabel'].replace('Category_1', '1')
data['ClassificationLabel'] = data['ClassificationLabel'].replace('Category_2', '2')
data['ClassificationLabel'] = data['ClassificationLabel'].replace('Category_3', '3')
data['ClassificationLabel'] = data['ClassificationLabel'].replace('Category_4', '4')
data['ClassificationLabel'] = data['ClassificationLabel'].replace('Category_5', '5')
data['ClassificationLabel'] = data['ClassificationLabel'].replace('Category_6', '6')

In [ ]:
data

Col1      Col2       Col3  \
0                      Word1 Word2 Word3 Word4 Word5  44912133   3,575.00   
1                                        Word6 Word7     10719   1,092.50   
2                    Word8 Word9 Word10 Word11 Word5  4.80Z+11         75   
3                                Word12 Word13 Word7     10731  30,980.00   
4                    Word8 Word9 Word10 Word11 Word5  4.80F+11   3,766.80   
...                                              ...       ...        ...   
5894                   Word177 Word178 Word147 Word7    180LSY  16,880.00   
5895                      Word16 Word17 Word18 Word7     BL398   4,200.00   
5896  Word212 Word213 Word214 Word125 Word119 Word39     74211        170   
5897                            Word148 Word75 Word5     11695  14,376.00   
5898                       Word40 Word41 Word4 Word5      1868   1,820.00   

                                       Col4        Col5  \
0                           Word771 Word772   8/31/2018   
1                   Word711 Word773 Word774   8/31/2018   
2                           Word775 Word776  10/31/2018   
3     Word777 Word45 Word160 Word45 Word778    1/1/2018   
4                   Word779 Word258 Word780    1/1/2018   
...                                     ...         ...   
5894               Word2127 Word705 Word825    3/1/2018   
5895          Word785 Word330 Word99 Word26   6/30/2018   
5896              Word1018 Word190 Word1403    1/1/2018   
5897                        Word846 Word991    4/1/2018   
5898       Word802 Word278 Word1242 Word803   7/31/2018   

                                         Col6 Col7 ClassificationLabel  
0             Word560 Word561 Word366 Word562    1                   1  
1                     Word563 Word366 Word562    0                   2  
2                Word563 Word564 Word9 Word26    0                   1  
3                             Word565 Word566    0                   1  
4             Word567 Word568 Word569 Word570    1                   1  
...                                       ...  ...                 ...  
5894                  Word576 Word366 Word562    3                   1  
5895             Word563 Word564 Word9 Word26    0                   1  
5896                  Word563 Word608 Word609    0                   2  
5897          Word560 Word561 Word315 Word638    1                   1  
5898  Word567 Word582 Word580 Word202 Word545    1                   1  

[5899 rows x 8 columns]

In [ ]:
#Col1

In [ ]:
col1 = data.Col1.values + ' ' + 'fakeword' + ' '

In [ ]:
joined_col1 = ' '

for i in tqdm(range(len(col1))):
  joined_col1 = joined_col1+col1[i]

100%|██████████| 5899/5899 [00:00<00:00, 744484.54it/s]


In [ ]:
col1_final = joined_col1.split('fakeword')

In [ ]:
col1_final = col1_final[:-1]

In [ ]:
col1_final[-1]

' Word40 Word41 Word4 Word5 '

In [ ]:
vectorizer = TfidfVectorizer()
x1 = vectorizer.fit_transform(col1_final)

In [ ]:
#Col6

In [ ]:
col6 = data.Col6.values + ' '+'fakeword'+' '

In [ ]:
joined_col6 = ' '

for i in tqdm(range(len(col6))):
  joined_col6 = joined_col6+col6[i]

100%|██████████| 5899/5899 [00:00<00:00, 794088.17it/s]


In [ ]:
col6_final = joined_col6.split('fakeword')

In [ ]:
col6_final = col6_final[:-1]

In [ ]:
col6_final[-1]

' Word567 Word582 Word580 Word202 Word545 '

In [ ]:
vectorizer = TfidfVectorizer()
x6 = vectorizer.fit_transform(col6_final)

In [ ]:
#Col7

In [ ]:
data['Col7'] = data['Col7'].replace('NoDoc', '0')
data['Col7'] = data['Col7'].replace('Doc1', '1')
data['Col7'] = data['Col7'].replace('Doc2', '2')
data['Col7'] = data['Col7'].replace('Doc3', '3')

In [ ]:
x7 = data['Col7'].values

In [ ]:
x7 = x7.reshape(-1,1)

In [ ]:
#Target

In [ ]:
y = data['ClassificationLabel'].values

In [ ]:
model1 = LogisticRegression(solver='lbfgs',max_iter=10000)
model2 = RandomForestClassifier(n_estimators=100, max_depth=5)
model3 = KNeighborsClassifier(n_neighbors=5,weights='distance')

In [ ]:
#Input feature = Col1

In [ ]:
#Logistic Regression
modelvalidation(model1,x1,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
1it [00:00,  1.76it/s]

[0.9245762711864407]


2it [00:00,  2.06it/s]

[0.9245762711864407, 0.9110169491525424]


3it [00:01,  2.08it/s]

[0.9245762711864407, 0.9110169491525424, 0.9203389830508475]


4it [00:01,  2.26it/s]

[0.9245762711864407, 0.9110169491525424, 0.9203389830508475, 0.9271186440677966]


5it [00:02,  2.19it/s]

[0.9245762711864407, 0.9110169491525424, 0.9203389830508475, 0.9271186440677966, 0.9126378286683631]


([0.9245762711864407,
  0.9110169491525424,
  0.9203389830508475,
  0.9271186440677966,
  0.9126378286683631],
 [array([[1030,   11,    0,    0,    0,    0,    0,    0,    0],
         [  66,   60,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    1,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    1,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    1,    0,    0,    0,    0,    0,    0],
         [   1,    0,    1,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0]]),
  array([[1005,   36,    0,    0,    0,    0,    0,    0,    0],
         [  57,   68,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    2,    0,    0,    0,    0,    0,    0],
         [   0,    0,    2,    0,    0,    0,    0,    0,    0],
         [   0,    1,    0,    0,    0,   

In [ ]:
#Random Forest
modelvalidation(model2,x1,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
1it [00:00,  2.83it/s]

[0.911864406779661]


2it [00:00,  2.73it/s]

[0.911864406779661, 0.911864406779661]


3it [00:01,  2.64it/s]

[0.911864406779661, 0.911864406779661, 0.9135593220338983]


4it [00:01,  2.74it/s]

[0.911864406779661, 0.911864406779661, 0.9135593220338983, 0.9110169491525424]


5it [00:01,  2.72it/s]

[0.911864406779661, 0.911864406779661, 0.9135593220338983, 0.9110169491525424, 0.910941475826972]


([0.911864406779661,
  0.911864406779661,
  0.9135593220338983,
  0.9110169491525424,
  0.910941475826972],
 [array([[1039,    2,    0,    0,    0,    0,    0,    0,    0],
         [  89,   37,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0]]),
  array([[1039,    2,    0,    0,    0,    0,    0,    0,    0],
         [  88,   37,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,

In [ ]:
#KNN
modelvalidation(model3,x1,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
1it [00:00,  2.48it/s]

[0.926271186440678]


2it [00:00,  2.87it/s]

[0.926271186440678, 0.9152542372881356]


3it [00:01,  3.10it/s]

[0.926271186440678, 0.9152542372881356, 0.9211864406779661]


4it [00:01,  3.15it/s]

[0.926271186440678, 0.9152542372881356, 0.9211864406779661, 0.9169491525423729]


5it [00:01,  3.10it/s]

[0.926271186440678, 0.9152542372881356, 0.9211864406779661, 0.9169491525423729, 0.9126378286683631]


([0.926271186440678,
  0.9152542372881356,
  0.9211864406779661,
  0.9169491525423729,
  0.9126378286683631],
 [array([[993,  48,   0,   0,   0,   0,   0,   0,   0],
         [ 27,  99,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   1,   0,   0,   0,   1,   0,   0],
         [  0,   1,   0,   0,   0,   0,   0,   0,   0],
         [  1,   0,   1,   0,   0,   0,   0,   0,   0],
         [  0,   1,   0,   0,   0,   0,   0,   0,   0],
         [  2,   0,   1,   0,   0,   0,   0,   0,   0],
         [  0,   1,   1,   0,   0,   0,   0,   0,   0],
         [  2,   0,   0,   0,   0,   0,   0,   0,   0]]),
  array([[1000,   39,    0,    0,    0,    0,    0,    1,    1],
         [  47,   78,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    2,    0,    0,    0,    0,    0,    0],
         [   0,    0,    2,    0,    0,    0,    0,    0,    0],
         [   0,    1,    0,    0,    0,    0,    0,    0,    0],
         [   0,    1,    0,    0,    0,    0,    0,    0,  

In [ ]:
#Input feature = Col6

In [ ]:
#Logistic Regression
modelvalidation(model1,x6,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
1it [00:00,  1.44it/s]

[0.9152542372881356]


2it [00:01,  1.95it/s]

[0.9152542372881356, 0.9186440677966101]


3it [00:01,  2.27it/s]

[0.9152542372881356, 0.9186440677966101, 0.9127118644067796]


4it [00:01,  2.66it/s]

[0.9152542372881356, 0.9186440677966101, 0.9127118644067796, 0.9135593220338983]


5it [00:02,  2.36it/s]

[0.9152542372881356, 0.9186440677966101, 0.9127118644067796, 0.9135593220338983, 0.9185750636132316]


([0.9152542372881356,
  0.9186440677966101,
  0.9127118644067796,
  0.9135593220338983,
  0.9185750636132316],
 [array([[1035,    6,    0,    0,    0,    0,    0,    0,    0],
         [  81,   45,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0]]),
  array([[1034,    7,    0,    0,    0,    0,    0,    0,    0],
         [  75,   50,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,   

In [ ]:
#Random Forest
modelvalidation(model2,x6,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
1it [00:00,  3.49it/s]

[0.8822033898305085]


2it [00:00,  3.75it/s]

[0.8822033898305085, 0.8822033898305085]


3it [00:00,  3.60it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085]


4it [00:01,  3.64it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8822033898305085]


5it [00:01,  3.58it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8821034775233249]


([0.8822033898305085,
  0.8822033898305085,
  0.8822033898305085,
  0.8822033898305085,
  0.8821034775233249],
 [array([[1041,    0,    0,    0,    0,    0,    0,    0,    0],
         [ 126,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0]]),
  array([[1041,    0,    0,    0,    0,    0,    0,    0,    0],
         [ 125,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,   

In [ ]:
#KNN
modelvalidation(model3,x6,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
1it [00:00,  3.00it/s]

[0.8796610169491526]


2it [00:00,  3.18it/s]

[0.8796610169491526, 0.9177966101694915]


3it [00:00,  3.29it/s]

[0.8796610169491526, 0.9177966101694915, 0.9076271186440678]


4it [00:01,  3.35it/s]

[0.8796610169491526, 0.9177966101694915, 0.9076271186440678, 0.9093220338983051]


5it [00:01,  3.32it/s]

[0.8796610169491526, 0.9177966101694915, 0.9076271186440678, 0.9093220338983051, 0.8744698897370653]


([0.8796610169491526,
  0.9177966101694915,
  0.9076271186440678,
  0.9093220338983051,
  0.8744698897370653],
 [array([[959,  81,   0,   0,   1,   0,   0,   0,   0],
         [ 49,  77,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   1,   0,   1,   0,   0,   0,   0],
         [  1,   0,   0,   0,   0,   0,   0,   0,   0],
         [  0,   0,   1,   0,   1,   0,   0,   0,   0],
         [  1,   0,   0,   0,   0,   0,   0,   0,   0],
         [  2,   0,   0,   0,   1,   0,   0,   0,   0],
         [  1,   0,   0,   0,   1,   0,   0,   0,   0],
         [  2,   0,   0,   0,   0,   0,   0,   0,   0]]),
  array([[1028,   11,    1,    0,    0,    0,    0,    1,    0],
         [  74,   51,    0,    0,    0,    0,    0,    0,    0],
         [   0,    0,    3,    0,    0,    0,    0,    0,    0],
         [   0,    0,    2,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   0,    1,    0,    0,    0,    0,    0,    0, 

In [ ]:
#Input feature = Col7

In [ ]:
#Logistic Regression
modelvalidation(model1,x7,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
1it [00:00,  1.12it/s]

[0.8822033898305085]


2it [00:01,  1.15it/s]

[0.8822033898305085, 0.8822033898305085]


3it [00:02,  1.28it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085]


4it [00:03,  1.41it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8822033898305085]


5it [00:03,  1.36it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8821034775233249]


([0.8822033898305085,
  0.8822033898305085,
  0.8822033898305085,
  0.8822033898305085,
  0.8821034775233249],
 [array([[1041,    0,    0,    0,    0,    0,    0,    0,    0],
         [ 126,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0]]),
  array([[1041,    0,    0,    0,    0,    0,    0,    0,    0],
         [ 125,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,   

In [ ]:
#Random Forest
modelvalidation(model2,x7,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
1it [00:00,  4.51it/s]

[0.8822033898305085]


2it [00:00,  4.69it/s]

[0.8822033898305085, 0.8822033898305085]


3it [00:00,  4.72it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085]


4it [00:00,  4.76it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8822033898305085]


5it [00:01,  4.72it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8821034775233249]


([0.8822033898305085,
  0.8822033898305085,
  0.8822033898305085,
  0.8822033898305085,
  0.8821034775233249],
 [array([[1041,    0,    0,    0,    0,    0,    0,    0,    0],
         [ 126,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0]]),
  array([[1041,    0,    0,    0,    0,    0,    0,    0,    0],
         [ 125,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,   

In [ ]:
#KNN
modelvalidation(model3,x7,y,5,123)

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
2it [00:00, 14.67it/s]

[0.8822033898305085]
[0.8822033898305085, 0.8822033898305085]
[0.8822033898305085, 0.8822033898305085, 0.8822033898305085]
[0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8822033898305085]


5it [00:00, 14.86it/s]

[0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8822033898305085, 0.8821034775233249]


([0.8822033898305085,
  0.8822033898305085,
  0.8822033898305085,
  0.8822033898305085,
  0.8821034775233249],
 [array([[1041,    0,    0,    0,    0,    0,    0,    0,    0],
         [ 126,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0]]),
  array([[1041,    0,    0,    0,    0,    0,    0,    0,    0],
         [ 125,    0,    0,    0,    0,    0,    0,    0,    0],
         [   3,    0,    0,    0,    0,    0,    0,    0,    0],
         [   2,    0,    0,    0,    0,    0,    0,    0,    0],
         [   1,    0,    0,    0,    0,   